### ISSUE TITLE
Error passing 2D np array to GenomeTrackBuilder, but a copy works.

### ISSUE THREAD

**Issue by parthgvora** [deepgenomics/GenomeKit#61]
# Description

When trying to build a gtrack with multiple dimensions, you have to pass a copy of the array to the `GenomeTrackBuilder` for it to work. If you pass the original array, you get the following error:

```
ValueError: src/py_genome_track.cpp:219: Data must have stride=1, consider making a copy with `np.array`
```

# Steps to Reproduce

```
def test():
    genome = gk.Genome("hg38")
    itvl = gk.Interval("chr1", "+", 1000000, 1000010, genome)
    data = np.vstack([np.arange(10, dtype=np.int8)] * 5).T

    track = gk.GenomeTrackBuilder(
        f"test.gtrack",
        "i8",
        "single_stranded",
        genome,
        dim=5,
    )
    track.set_default_value(0)

    # this breaks
    # track.set_data(itvl, data)
    # track.finalize()

    # this works
    track.set_data(itvl, data.copy())
    track.finalize()
```

**Comment by ovesh** [comment]
The error in question comes from code that prevents users from passing a strided array to track.set_data().

I'll look into why it thinks that this data is strided. I suspect it's the transposition (`.T`). For example, this works:
```
itvl = gk.Interval("chr1", "+", 1000000, 1000005, genome)
data = np.vstack([np.arange(10, dtype=np.int8)] * 5)
track = gk.GenomeTrackBuilder(f"test.gtrack", "i8", "single_stranded", genome, dim=10)
```

**Comment by ovesh** [comment]
Closing. The error message is clear enough to steer users to a solution, and the effort to support strided data isn't justified at this point.
